Parameters:
  InstanceType:
    Type: String
    Default: db.r5.8xlarge
 # Network
  VPC:
    Description: Default VPC.
    Type: AWS::EC2::VPC::Id
    Default: vpc-661ab703
Resources:
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: qa-clone-SG
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          CidrIp: 0.0.0.0/0
          Description: For traffic from Internet
      GroupDescription: Security Group for demo server
      VpcId: !Ref VPC
  DBCluster:
    DeletionPolicy: Snapshot # default
    UpdateReplacePolicy: Snapshot
    Type: AWS::RDS::DBCluster
    Properties:
      RestoreType: copy-on-write
      UseLatestRestorableTime: true   
      SourceDBClusterIdentifier: auroraprodplanhub-cluster
      DBClusterIdentifier: qaauroraplanhub-clone-cluster
      VpcSecurityGroupIds: 
       - !Ref SecurityGroup
  DBInstance:
    Type: AWS::RDS::DBInstance
    DependsOn: DBCluster
    Properties:
      DBClusterIdentifier: !Ref DBCluster
      Engine: aurora-mysql
      DBInstanceClass: !Ref InstanceType
      DBInstanceIdentifier: auroraqaplanhub-instance
      PubliclyAccessible: true
  EC2InstanceDemoSvr:
    Type: 'AWS::EC2::Instance'
    Properties:
      AvailabilityZone: us-west-2c
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            DeleteOnTermination: 'true'
            VolumeSize: '500'
            VolumeType: gp2
      ImageId: ami-05f86921d692cb088
      InstanceType: c5.4xlarge
      KeyName: planhubserverkey
      UserData: 
       Fn::Base64: |
        #!/bin/sh
	      apt install software-properties-common apt-transport-https -y
        add-apt-repository ppa:openjdk-r/ppa -y
        apt install openjdk-8-jdk -y
        update-alternatives --config java
        sudo adduser jenkins --gecos "First Last,RoomNumber,WorkPhone,HomePhone" --disabled-password
        echo "jenkins:admin123" | sudo chpasswd
        cat <<'EOF' > /etc/apache2/sites-available/planhub-frontend-waf.conf
        <VirtualHost *:80>
        ServerName qa1.planhub.com
        ServerAlias qa1.planhub.com
        DocumentRoot /var/www/html/frontend-planhub-new/dist
        ErrorLog ${APACHE_LOG_DIR}/error.log
      	CustomLog ${APACHE_LOG_DIR}/access.log cloudwatch
        RewriteEngine On
        RewriteCond %{HTTP:X-Forwarded-Proto} =http
        RewriteRule .* https://%{HTTP:Host}%{REQUEST_URI} [L,R=permanent]
        </VirtualHost>
        <VirtualHost *:443>
        DocumentRoot /var/www/html/frontend-planhub-new/dist
        ServerName app.planhub.com
        ServerAlias app.planhub.com
        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log cloudwatch
        RewriteEngine On
        RewriteRule ^#/(.*)$ $1
        SSLEngine on
        SSLCertificateFile /etc/apache2/ssl/NEW_STAR_planhub_com.crt
        SSLCertificateKeyFile /etc/apache2/ssl/new_star.planhub.com.key
        SSLCertificateChainFile  /etc/apache2/ssl/planhub_intermediate.crt
        SSLCipherSuite HIGH:+MEDIUM:!SSLv2:!EXP:!ADH:!aNULL:!eNULL:!NULL
        Header always set Strict-Transport-Security "max-age=63072000;"
        SSLProtocol all -SSLv2 -SSLv3
        SSLHonorCipherOrder on
        SSLCipherSuite "EECDH+ECDSA+AESGCM EECDH+aRSA+AESGCM EECDH+ECDSA+SHA384 EECDH+ECDSA+SHA256 EECDH+aRSA+S$
        <Directory  /var/www/html/frontend-planhub-new>
        AllowOverride All
        Require all granted
        RewriteEngine On
        RewriteRule ^(.*)$ $1
        </Directory>
        <IfModule mod_deflate.c>
        SetOutputFilter DEFLATE
        AddOutputFilterByType DEFLATE text/plain
        AddOutputFilterByType DEFLATE text/html
        AddOutputFilterByType DEFLATE text/xml
        AddOutputFilterByType DEFLATE text/css
        AddOutputFilterByType DEFLATE application/xml
        AddOutputFilterByType DEFLATE application/xhtml+xml
        AddOutputFilterByType DEFLATE application/rss+xml
        AddOutputFilterByType DEFLATE application/javascript
        AddOutputFilterByType DEFLATE application/x-javascript
        SetEnvIfNoCase Request_URI .(?:exe|t?gz|zip|iso|tar|bz2|sit|rar) no-gzip dont-vary
        SetEnvIfNoCase Request_URI .(?:gif|jpe?g|jpg|ico|png)  no-gzip dont-vary
        SetEnvIfNoCase Request_URI .pdf no-gzip dont-vary
        BrowserMatch ^Mozilla/4 gzip-only-text/html
        BrowserMatch ^Mozilla/4.0[678] no-gzip
        BrowserMatch \bMSIE !no-gzip !gzip-only-text/html
        Header append Vary User-Agent env=!dont-vary
        DeflateFilterNote Input instr
        DeflateFilterNote Output outstr
        DeflateFilterNote Ratio ratio
        LogFormat '"%r" %{outstr}n/%{instr}n %{ratio}n%%' DEFLATE
        CustomLog logs/deflate_log DEFLATE
        </IfModule>
        </VirtualHost>
        EOF
        cat <<'EOF' > /etc/apache2/sites-available/planhub-frontend-waf.conf
        <VirtualHost *:80>
        ServerName qa1.api.planhub.com
        ServerAlias qa1.api.planhub.com 
        DocumentRoot /var/www/html/api-planhub/public   
        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log cloudwatch
        RewriteEngine On
        RewriteCond %{HTTP:X-Forwarded-Proto} =http
        RewriteRule .* https://%{HTTP:Host}%{REQUEST_URI} [L,R=permanent]
        </VirtualHost>
        <VirtualHost *:443>
        DocumentRoot /var/www/html/api-planhub/public
        ServerName api.planhub.com
        ServerAlias api.planhub.com
        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log cloudwatch
        SSLEngine on
        SSLCertificateFile /etc/apache2/ssl/NEW_STAR_planhub_com.crt
        SSLCertificateKeyFile /etc/apache2/ssl/new_star.planhub.com.key
        SSLCertificateChainFile  /etc/apache2/ssl/planhub_intermediate.crt
        SSLCipherSuite HIGH:+MEDIUM:!SSLv2:!EXP:!ADH:!aNULL:!eNULL:!NULL
        Header always set Strict-Transport-Security "max-age=63072000;"
        SSLProtocol all -SSLv2 -SSLv3
        SSLHonorCipherOrder on
        SSLCipherSuite "EECDH+ECDSA+AESGCM EECDH+aRSA+AESGCM EECDH+ECDSA+SHA384 EECDH+ECDSA+SHA256 EECDH+aRSA+S$
        <Directory /var/www/html/api-planhub/public>
        AllowOverride All
        Options Indexes FollowSymLinks
        Require all granted
        RewriteEngine On
        RewriteBase /
        RewriteCond %{RREQUEST_FILENAME} !-d
        RewriteCond %{REQUEST_FILENAME} !-f
        RewriteRule ^ index.php [QSA,L]
        RewriteRule .*\.(pdf|css|gif|png|bmp)$ - [F,NC]
        RewriteCond %{REQUEST_METHOD} OPTIONS
        RewriteRule ^(.*)$ $1 [R=200,L]
        </Directory>
        <IfModule mod_deflate.c>
        SetOutputFilter DEFLATE
        AddOutputFilterByType DEFLATE text/plain
        AddOutputFilterByType DEFLATE text/html
        AddOutputFilterByType DEFLATE text/xml
        AddOutputFilterByType DEFLATE text/css
        AddOutputFilterByType DEFLATE text/xml
        AddOutputFilterByType DEFLATE text/css
        AddOutputFilterByType DEFLATE application/xml
        AddOutputFilterByType DEFLATE application/xhtml+xml
        AddOutputFilterByType DEFLATE application/rss+xml
        AddOutputFilterByType DEFLATE application/javascript
        AddOutputFilterByType DEFLATE application/x-javascript
        SetEnvIfNoCase Request_URI .(?:exe|t?gz|zip|iso|tar|bz2|sit|rar) no-gzip dont-vary
        SetEnvIfNoCase Request_URI .(?:gif|jpe?g|jpg|ico|png)  no-gzip dont-vary
        SetEnvIfNoCase Request_URI .pdf no-gzip dont-vary
        BrowserMatch ^Mozilla/4 gzip-only-text/html
        BrowserMatch ^Mozilla/4.0[678] no-gzip
        BrowserMatch \bMSIE !no-gzip !gzip-only-text/html
        Header append Vary User-Agent env=!dont-vary
        DeflateFilterNote Input instr
        DeflateFilterNote Output outstr
        DeflateFilterNote Ratio ratio
        LogFormat '"%r" %{outstr}n/%{instr}n %{ratio}n%%' DEFLATE
        CustomLog logs/deflate_log DEFLATE
        Header set Access-Control-Allow-Origin "*"
        </IfModule> 
        </VirtualHost>
        systemctl restart apache2
      NetworkInterfaces:
        - Description: Primary network interface
          DeviceIndex: '0'
          SubnetId: subnet-8003f9d9
          PrivateIpAddress: 172.31.6.199
          GroupSet:
            - !Ref SecurityGroupDemoSvrTraffic
